export const gameTexts: string[] = [
  'Chciałbym zgłosić producenta mortadeli, firmę "Smaczna Mortadela", która nie zaznaczyła, że ich produkt nie nadaje się do wypieków makowca. Dnia 6 lipca 2024 r. próbowałem użyć mortadeli tej firmy do wypieku makowca, co skończyło się katastrofą kulinarną. Uważam, że firma powinna informować klientów o ograniczeniach swoich produktów. Proszę o podjęcie stosownych działań, aby zapobiec dalszym incydentom i zapewnić mi poczucie bezpieczeństwa.',
  'Chciałbym zgłosić kradzież makowca przez mojego sąsiada, Piotra Malinowskiego, zamieszkałego przy ul. Fikcyjnej 8. Dnia 3 lipca 2024 r. zauważyłem, że zniknął makowiec, który zostawiłem na parapecie do ostygnięcia. Podejrzewam, że to sprawka Piotra Malinowskiego, z którym od pewnego czasu mam napięte relacje sąsiedzkie. Proszę o podjęcie stosownych działań, aby zapobiec dalszym kradzieżom i zapewnić mi poczucie bezpieczeństwa.',
  'Chciałbym zgłosić podejrzane zachowanie mojej sąsiadki, Anny Kowalskiej, zamieszkałej przy ul. Fikcyjnej 3. Dnia 2 lipca 2024 r. zauważyłem, że nagle doznałem paraliżu kończyn dolnych po spotkaniu z nią. Podejrzewam, że mogła użyć jakiejś substancji, aby wywołać ten stan. Obawiam się o swoje zdrowie i bezpieczeństwo. Proszę o podjęcie stosownych działań, aby zapobiec dalszym incydentom i zapewnić mi poczucie bezpieczeństwa.',
  'Chciałbym zgłosić akt wandalizmu dokonany przez mojego sąsiada, Adama Nowaka, zamieszkałego przy ul. Fikcyjnej 5. Dnia 5 lipca 2024 r. odkryłem, że ktoś odkręcił koła od mojego wózka inwalidzkiego, który stał przed moim mieszkaniem na ul. Przykładowej 10. Podejrzewam, że to sprawka Adama Nowaka, z którym od pewnego czasu mam napięte relacje sąsiedzkie. Proszę o podjęcie stosownych działań, aby zapobiec dalszym aktom wandalizmu i zapewnić mi poczucie bezpieczeństwa.',
  'Chciałbym zgłosić używanie nielegalnych składników do wypieku makowca przez moją sąsiadkę, Zofię Nowicką, zamieszkałą przy ul. Fikcyjnej 12. Dnia 1 lipca 2024 r. zauważyłem, że Zofia Nowicka dodaje do makowca podejrzane substancje, które wyglądają na nielegalne. Obawiam się, że spożywanie tych wypieków może być niebezpieczne. Proszę o podjęcie stosownych działań, aby zapewnić nam bezpieczeństwo i zgodność z prawem.',
  'Chciałbym zgłosić dziwne zachowanie mojego sąsiada, Marka Kwiatkowskiego, zamieszkałego przy ul. Fikcyjnej 9. Dnia 6 lipca 2024 r. zauważyłem, że chodzi po okolicy w czapce piekarza, choć nigdy nie widziałem go piekącego. Wygląda to podejrzanie i budzi moje obawy o jego stan psychiczny. Proszę o podjęcie stosownych działań, aby zapewnić nam bezpieczeństwo i sprawdzić, czy Marek Kwiatkowski nie potrzebuje pomocy.',
  'Chciałbym zgłosić sprzedaż słabej jakości makowca przez mojego sąsiada, Marka Kowalskiego, który prowadzi sklep przy ul. Fikcyjnej 7. Dnia 10 lipca 2024 r. kupiłem makowiec w jego sklepie, który okazał się być twardy i niesmaczny. Podejrzewam, że Marek Kowalski używa przeterminowanych składników do wypieków. Proszę o podjęcie stosownych działań, aby zapobiec dalszym incydentom.',
  'Chciałbym zgłosić kradzież mortadeli przez moją sąsiadkę, Annę Nowak, zamieszkałą przy ul. Fikcyjnej 3. Dnia 9 lipca 2024 r. zauważyłem, że zniknęła mortadela, którą przechowywałem w lodówce na wspólnym korytarzu. Podejrzewam, że to sprawka Anny Nowak, która była widziana w okolicy lodówki w tym czasie. Proszę o podjęcie stosownych działań, aby zapobiec dalszym incydentom.',
  'Chciałbym zgłosić sprzedaż słabej jakości mortadeli przez sklep prowadzony przez Jana Wiśniewskiego, znajdujący się przy ul. Fikcyjnej 5. Dnia 8 lipca 2024 r. kupiłem mortadelę w jego sklepie, która okazała się być wodnista i miała nieprzyjemny zapach. Podejrzewam, że Jan Wiśniewski sprzedaje produkty niskiej jakości, co może być niebezpieczne dla zdrowia klientów. Proszę o podjęcie stosownych działań, aby zapobiec dalszym incydentom.',
  'Chciałbym zgłosić dziwne zachowanie mojego sąsiada, Jakuba Wiśniewskiego, zamieszkałego przy ul. Fikcyjnej 7. Dnia 4 lipca 2024 r. zauważyłem, że gotuje ziemniaki w lampie ulicznej przed swoim domem. Jest to nie tylko niebezpieczne, ale i dziwaczne. Podejrzewam, że Jakub Wiśniewski może stanowić zagrożenie dla siebie i innych mieszkańców. Proszę o podjęcie stosownych działań, aby zapobiec takim sytuacjom i zapewnić nam bezpieczeństwo.',
  'Chciałbym zgłosić brak wypieków w sprzedaży sklepu przy ul. Fikcyjnej 9, mimo że pracownicy noszą tam czapki piekarza. Dnia 7 lipca 2024 r. wszedłem do sklepu w poszukiwaniu świeżego pieczywa, ale okazało się, że nie było tam żadnych wypieków. To działanie wprowadza klientów w błąd i jest nieuczciwe. Proszę o podjęcie stosownych działań, aby zapobiec dalszym incydentom.',
];
